### ISSUE TITLE
Значение pi

### ISSUE THREAD

**Issue by slemeshevsky** [Lenigard/SpecialCource_Labs#1]
В файле [area_and_circumference.py](https://github.com/Lenigard/SpecialCource_Labs/blob/master/1_firstSteps/area_and_circumference.py)

для получения значения pi добавлен импорт numpy
Как и откуда еще можно импортировать знчение   pi?

**Comment by Lenigard** [comment]
Можно использовать библиотеку math, в которой тоже хранится pi.
Также можно добавить не всю библиотеку, а только само значение pi путём записи:
from math(numpy) import pi
